defaults:
  - _self_

# experiment
experiment: crespt
feature_dim: 128
use_cf: True
cf_weight: 1.0
rsd_discount: 0.9
save_dir: ~

agent:
  _target_: crespt.Agent
  obs_shape: ??? # to be specified later
  action_shape: ??? # to be specified later
  device: ${device}
  use_cf: ${use_cf}
  lr: ${lr}
  actor_update_times: ${actor_update_times}
  critic_update_times: ${critic_update_times}
  critic_target_tau: 0.01
  critic_target_update_freq: ${critic_target_update_freq}
  update_every_steps: 1
  use_tb: ${use_tb}
  num_expl_steps: 2000
  hidden_dim: 1024
  feature_dim: ${feature_dim}
  init_temperature: 0.1
  rsd_nstep: 5 # >= nstep
  rsd_discount: ${rsd_discount}
  cf_temp: 0.1
  cf_output_dim: 7
  cf_elite_num: 5
  cf_output_mode: min # choices=['min', 'max', 'random']
  cf_weight: ${cf_weight}
  cf_update_freq: 10
  omega_num_sample: 256
  omega_cf_output_mode: ~ # choices=[None, 'min_mu', 'min_all', 'sample']
