defaults:
  - _self_

train_mode: online
num_train_frames: 500001
nstep: 1
show_train_stats_every_frames: 2000
batch_size: 512
actor_lr: 5e-4
critic_lr: 5e-4
encoder_lr: 5e-4
replay_buffer_size: 1_000_000
task_name: walker_walk_random

actor_update_times: 1
critic_update_times: 1
critic_target_update_freq: 2

rsd_discount: ~

rew_noise: ~
rew_noise_mu: 0.0
rew_noise_std: 1.0
